sonar.projectKey=shyamchauhansimform_ci_cd_sec
sonar.organization=shyamchauhansimform

sonar.projectName=ci_cd_sec
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/*.yml,**/*.toml,**/.git/**

sonar.python.version=3
